In [1]:
import numpy as np
list = [2,4,5,6]
array1 = np.array(list)
print(array1)

[2 4 5 6]


In [3]:
# create an array with 4 elements filled with zeros
array1 = np.zeros(100)
print(array1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]


In [4]:
# create an array with values from 0 to 4
array1 = np.arange(5)
print(array1)

[0 1 2 3 4]


In [5]:
# create an array with values from 1 to 8 with step 2
array2 = np.arange(1,9,2)
print(array2)

[1 3 5 7]


In [6]:
# create an array with random numbers
array1 = np.random.rand(5)
print(array1)

[0.56879945 0.78033175 0.08963031 0.53108134 0.67374903]


In [10]:
# create 2D array with 2 rows and 4 column
array1 = np.array([[1,2,3,4], [5,6,7,8]])
print(array1.ndim)
print(array1.shape)

2
(2, 4)


In [12]:
# creating 2D array with elements initialized to 5
numpy_array = np.full((2,2),5)
print(numpy_array)

[[5 5]
 [5 5]]


In [14]:
print(numpy_array.ndim)
print(numpy_array.size)
print(numpy_array.dtype)
print(numpy_array.shape)
print(numpy_array.itemsize)
print(numpy_array.data)

2
4
int64
(2, 2)
8


In [18]:
array1 = np.array([1,2,3,4,5,6,7,8])
result = np.reshape(array1, (2,4))
print(result)
result = np.reshape(array1, (4,2))
print(result)


[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [19]:
print(np.reshape(array1, (2,2,2)))

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [21]:
math_marks = np.array([1,2,3,4])
science_marks = np.array([2,4,6,8])
score = math_marks + science_marks
print(score)

[ 3  6  9 12]


In [23]:
# output using the add function
total_marks = np.add(math_marks, science_marks)
print(total_marks)

[ 3  6  9 12]


In [24]:
# comparison operator
array1 = np.array([1,2,3])
array2 = np.array([3,2,1])
result = array1 < array2
print(result)

[ True False False]


In [25]:
# comparison function
print(np.less(array1, array2))

[ True False False]
