In [38]:
import numpy as np
print(np.__version__)

2.2.4


Convert python list (if we already have) into numpy array

In [39]:
my_list_1d = [5,3,8]

In [40]:
# convert python list into 1-dimensional numpy array
np.array(my_list_1d)

array([5, 3, 8])

In [41]:
# 2-dimensional array from list of lists
my_list_2d = [[3,7,10], [4,2,5]]
print(my_list_2d)

[[3, 7, 10], [4, 2, 5]]


In [42]:
my_2d_array = np.array(my_list_2d) # 3,7,10 are 1st row and 4,2,5 are 2nd row ---- 3,4 are 1st column and so on
my_2d_array

array([[ 3,  7, 10],
       [ 4,  2,  5]])

Create numpy array incase we don't have list

In [43]:
my_2d_array[0][2] # will print 10
my_2d_array[1][1] # will print 2

np.int64(2)

In [44]:
3 * my_list_2d

[[3, 7, 10], [4, 2, 5], [3, 7, 10], [4, 2, 5], [3, 7, 10], [4, 2, 5]]

In [45]:
2 * my_list_1d

[5, 3, 8, 5, 3, 8]

In [46]:
3 * np.array(my_list_1d) # All list item get multiplied by 3

array([15,  9, 24])

## Working with Vectors in Numpy

### Creating Vectors and Extracting Values

In [96]:
import numpy as np
one_dimension_vector = np.array([4, 8, 15, 16, 23, 42])
print(one_dimension_vector)

[ 4  8 15 16 23 42]


In [97]:
one_dimension_vector.shape

(6,)

In [98]:
one_dimension_vector.ndim

1

In [101]:
first_element = one_dimension_vector[0]
print(first_element)

4


In [103]:
last_element = one_dimension_vector[-1]
print(last_element)

42


In [104]:
one_dimension_vector[0] = 100

In [105]:
one_dimension_vector

array([100,   8,  15,  16,  23,  42])

In [53]:
# Creating vector with np.arange

In [108]:
martrix = np.array([[1,2,3],[4,5,6]])
martrix.ndim

2

In [55]:
vector_using_nrange = np.arange(0,10)
vector_using_nrange

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
vector_using_nrange.shape

(10,)

In [109]:
row_vector = np.array([[1,2,3]])

In [110]:
row_vector.shape

(1, 3)

In [111]:
row_vector.ndim

2

In [112]:
two_dimensional_array = np.array([[1.,2.,3.],[4.,5.,6.]])

In [61]:
two_dimensional_array.shape

(2, 3)

In [73]:
two_dimensional_array.ndim

2

In [77]:
two_dimensional_array_matrix_shape = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [78]:
two_dimensional_array_matrix_shape.shape

(3, 3)

In [113]:
three_dimensional_batch_of_2d_matrix = np.array([
    [[1,2,3],[3,4,5]],
    [[5,6,7],[7,8,9]]
])

In [114]:
three_dimensional_batch_of_2d_matrix.shape

(2, 2, 3)

In [115]:
three_dimensional_batch_of_2d_matrix.ndim

3

In [91]:
four_dimensional_array = np.array([
    [
        [[1,2,3]]
    ]
])

In [92]:
four_dimensional_array.shape

(1, 1, 1, 3)