# Working with Vectors in Numpy

## Creating Vectors and Extracting Values

In [15]:
# Basic Creation with np.array
import numpy as np
list_of_numbers = [4,8,15,16,23]
array = np.array(list_of_numbers)
print(array)

[ 4  8 15 16 23]


In [16]:
type(array)

numpy.ndarray

In [17]:
array.shape

(5,)

In [22]:
print(array.ndim)

1


In [24]:
# Extract Values
first_element = array[0]
print(first_element)
print(array[4]) # Last element
print(array[-1]) # Last element

4
23
23


In [27]:
# Setting values
array[0] = 100
print(array)
array[-1] = 50
print(array)

[100   8  15  16  23]
[100   8  15  16  50]


In [ ]:
# Creating vectors with np.arange
sequential_numbers = np.arange(17)